/** Dados da viagem — Paris 5 dias */
const TRIP = {
  title: "Viagem à Paris",
  subtitle: "5 dias inesquecíveis",
  cambio: 6.2,
  navigoSemanal: 32.4,
  dicasGerais: [
    "Passe Navigo semanal (€32,40) cobre metrô, Disney e aeroporto se for seg–dom.",
    "Reserve Louvre, Torre Eiffel e Disney com antecedência pelo celular.",
    "Leve casaco leve — Paris pode esfriar à noite, mesmo no verão.",
    "Água da torneira é potável. Peça 'une carafe d'eau' no restaurante.",
  ],
};

const IMAGES = {
  aeroporto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Paris_-_Aerial_View%2C_La_Defense%2C_Eiffel_Tower%2C_Trocad%C3%A9ro%2C_Tour_Montparnasse%2C_Notre-Dame%2C_Les_Invalides%2C_Arc_de_Triomphe%2C_Louvre%2C_Sacr%C3%A9-C%C5%93ur%2C_Montmartre%2C_2015.jpg/800px-thumbnail.jpg",
  bairro: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Street_in_Le_Marais%2C_Paris%2C_France.jpg/800px-Street_in_Le_Marais%2C_Paris%2C_France.jpg",
  notredame: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Notre-Dame_de_Paris%2C_4_October_2017.jpg/800px-Notre-Dame_de_Paris%2C_4_October_2017.jpg",
  seine: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Panorama_Pont_Neuf_%28Paris%29.jpg/800px-Panorama_Pont_Neuf_%28Paris%29.jpg",
  jantar: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Paris_cafe_terrace.jpg/800px-Paris_cafe_terrace.jpg",
  cafe: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Croissant-Petit-Dejeuner.jpg/800px-Croissant-Petit-Dejeuner.jpg",
  louvre: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/800px-Louvre_Museum_Wikimedia_Commons.jpg",
  tuileries: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Tuileries_Garden%2C_Paris%2C_France_-_panoramio.jpg/800px-Tuileries_Garden%2C_Paris%2C_France_-_panoramio.jpg",
  torre: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/800px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg",
  trocadero: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Tour_Eiffel%2C_Paris%2C_from_Trocadero%2C_June_2010.jpg/800px-Tour_Eiffel%2C_Paris%2C_from_Trocadero%2C_June_2010.jpg",
  arco: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Arc_de_Triomphe%2C_Paris_7_June_2014%2C_perspective-2.jpg/800px-Arc_de_Triomphe%2C_Paris_7_June_2014%2C_perspective-2.jpg",
  champs: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Champs-Elysees_Daytime_%28cropped%29.jpg/800px-Champs-Elysees_Daytime_%28cropped%29.jpg",
  montmartre: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sacre_Coeur_paris.jpg/800px-Sacre_Coeur_paris.jpg",
  disney: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Sleeping_Beauty_Castle_%28cropped%29.jpg/800px-Sleeping_Beauty_Castle_%28cropped%29.jpg",
  orsay: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Le_Mus%C3%A9e_d%27Orsay%2C_Paris_May_2010.jpg/800px-Le_Mus%C3%A9e_d%27Orsay%2C_Paris_May_2010.jpg",
  compras: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Galeries_Lafayette_dome%2C_Paris%2C_France.jpg/800px-Galeries_Lafayette_dome%2C_Paris%2C_France.jpg",
  hotel: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/H%C3%B4tel_des_Invalides%2C_Paris%2C_France.jpg/800px-H%C3%B4tel_des_Invalides%2C_Paris%2C_France.jpg",
};

const DAYS = [
  {
    id: 1,
    emoji: "✈️",
    weekday: "Segunda-feira",
    title: "Chegada e Paris Clássico",
    color: "#1F4E79",
    accent: "#D6E4F0",
    date: "",
    summary: "Dia leve para descansar do voo e conhecer o centro histórico.",
    activities: [
      {
        time: "Manhã",
        title: "Chegada e hotel",
        place: "Aeroporto → Hotel",
        desc: "Chegada em CDG ou Orly. Check-in ou deixe as malas no hotel.",
        transport: "RER B ou Navigo",
        priceEur: "0 – 14",
        priceNote: "Navigo semanal inclui se já estiver ativo",
        image: IMAGES.aeroporto,
        link: { label: "Navigo semanal", url: "https://www.iledefrance-mobilites.fr/en/tickets-fares/detail/navigo-weekly-ticket" },
      },
      {
        time: "11h – 13h",
        title: "Passeio pelo bairro",
        place: "Marais / Saint-Germain",
        desc: "Caminhada tranquila pelo bairro do hotel e almoço leve.",
        transport: "A pé / metrô",
        priceEur: "15",
        image: IMAGES.bairro,
      },
      {
        time: "14h – 16h",
        title: "Notre-Dame e Île de la Cité",
        place: "Île de la Cité",
        desc: "Catedral Notre-Dame (exterior) e Sainte-Chapelle opcional.",
        transport: "Metrô linha 4",
        priceEur: "0 – 16",
        priceNote: "Sainte-Chapelle ~€16",
        image: IMAGES.notredame,
        link: { label: "Reservar Notre-Dame", url: "https://www.notredamedeparis.fr/en/visit/opening-times-and-access" },
      },
      {
        time: "16h30 – 18h",
        title: "Passeio pelo Sena",
        place: "Pont Neuf → Louvre",
        desc: "Caminhada à beira do rio Sena até a praça do Louvre.",
        transport: "A pé",
        priceEur: "0",
        image: IMAGES.seine,
        link: { label: "Info Louvre", url: "https://www.louvre.fr/en/visit/hours-admission" },
      },
      {
        time: "19h – 21h",
        title: "Jantar e descanso",
        place: "Bistro perto do hotel",
        desc: "Primeira noite — jantar tranquilo e descanso para o jet lag.",
        transport: "Metrô",
        priceEur: "20 – 35",
        image: IMAGES.jantar,
      },
    ],
  },
  {
    id: 2,
    emoji: "🎨",
    weekday: "Terça-feira",
    title: "Louvre e Torre Eiffel",
    color: "#2E7D32",
    accent: "#E2EFDA",
    date: "",
    summary: "O dia mais icônico — museu de manhã, Torre ao entardecer.",
    activities: [
      {
        time: "08h30",
        title: "Café da manhã",
        place: "Padaria do bairro",
        desc: "Croissant e café numa boulangerie parisiense.",
        transport: "A pé",
        priceEur: "8",
        image: IMAGES.cafe,
      },
      {
        time: "09h30 – 13h",
        title: "Museu do Louvre",
        place: "Louvre",
        desc: "Mona Lisa, Vênus de Milo e ala Denon. Reserva obrigatória!",
        transport: "Metrô 1 / 7",
        priceEur: "22",
        priceNote: "Grátis 1ª sexta 18h–21h45 (exc. jul/ago)",
        image: IMAGES.louvre,
        highlight: true,
        link: { label: "Reservar Louvre", url: "https://ticket.louvre.fr/en" },
      },
      {
        time: "13h – 14h",
        title: "Almoço",
        place: "Carrousel du Louvre",
        desc: "Almoço no shopping subterrâneo ou nos jardins.",
        transport: "A pé",
        priceEur: "15",
        image: IMAGES.tuileries,
      },
      {
        time: "14h30 – 16h",
        title: "Jardim das Tuileries",
        place: "Tuileries → Concorde",
        desc: "Passeio pelos jardins até Place de la Concorde.",
        transport: "A pé",
        priceEur: "0",
        image: IMAGES.tuileries,
      },
      {
        time: "16h30 – 18h30",
        title: "Torre Eiffel",
        place: "7º arrondissement",
        desc: "Subir ao topo da Torre Eiffel — reserva online essencial.",
        transport: "Metrô 6 / RER C",
        priceEur: "28 – 37",
        priceNote: "Topo ~€37 | Escadas+elevador ~€28",
        image: IMAGES.torre,
        highlight: true,
        link: { label: "Reservar Torre", url: "https://ticket.toureiffel.paris/en" },
      },
      {
        time: "19h – 21h",
        title: "Pôr do sol no Trocadéro",
        place: "Trocadéro",
        desc: "Vista clássica da Torre iluminada + jantar.",
        transport: "Metrô 6",
        priceEur: "25",
        image: IMAGES.trocadero,
      },
    ],
  },
  {
    id: 3,
    emoji: "🏛️",
    weekday: "Quarta-feira",
    title: "Arco e Montmartre",
    color: "#E65100",
    accent: "#FCE4D6",
    date: "",
    summary: "Arco do Triunfo de manhã, Montmartre à tarde.",
    activities: [
      {
        time: "09h",
        title: "Café da manhã",
        place: "Hotel",
        transport: "—",
        priceEur: "8",
        image: IMAGES.cafe,
      },
      {
        time: "09h30 – 11h",
        title: "Arco do Triunfo",
        place: "Place Charles de Gaulle",
        desc: "Subir ao terraço — vista das 12 avenidas de Paris.",
        transport: "Metrô 1 / 2 / 6",
        priceEur: "16 – 22",
        priceNote: "Quarta abr–set: €16",
        image: IMAGES.arco,
        highlight: true,
        link: { label: "Reservar Arco", url: "https://www.paris-arc-de-triomphe.fr/en/booking/book-a-ticket" },
      },
      {
        time: "11h – 13h",
        title: "Champs-Élysées",
        place: "Av. Champs-Élysées",
        desc: "Caminhada pela avenida mais famosa até Place de la Concorde.",
        transport: "A pé",
        priceEur: "0",
        image: IMAGES.champs,
      },
      {
        time: "13h – 14h",
        title: "Almoço — menu do dia",
        place: "Bistro",
        desc: "Formule: prato + sobremesa, geralmente €14–18.",
        transport: "Metrô",
        priceEur: "15",
        image: IMAGES.jantar,
      },
      {
        time: "14h30 – 16h",
        title: "Galerias Lafayette",
        place: "9º arrondissement",
        desc: "Opcional — terraço com vista grátis da cúpula.",
        transport: "Metrô 7 / 9",
        priceEur: "0",
        image: IMAGES.compras,
        link: { label: "Galerias Lafayette", url: "https://www.galerieslafayette.com/en/" },
      },
      {
        time: "16h30 – 19h",
        title: "Montmartre",
        place: "Sacré-Cœur",
        desc: "Basílica, Place du Tertre e Moulin Rouge (por fora).",
        transport: "Metrô 2 / 12",
        priceEur: "0",
        image: IMAGES.montmartre,
        highlight: true,
      },
      {
        time: "19h30",
        title: "Jantar em Montmartre",
        place: "Montmartre",
        transport: "Metrô",
        priceEur: "25",
        image: IMAGES.jantar,
      },
    ],
  },
  {
    id: 4,
    emoji: "🏰",
    weekday: "Quinta-feira",
    title: "Disneyland Paris",
    color: "#6A1B9A",
    accent: "#E4DFEC",
    date: "",
    summary: "Dia inteiro na Disney — saia cedo!",
    activities: [
      {
        time: "07h30",
        title: "Café rápido",
        place: "Hotel",
        desc: "Pequeno-almoço + lanche para levar ao parque.",
        priceEur: "8",
        image: IMAGES.cafe,
      },
      {
        time: "08h00",
        title: "Trem para Disney",
        place: "RER A → Chessy",
        desc: "Viagem de ~45 min até Marne-la-Vallée.",
        transport: "RER A (Navigo)",
        priceEur: "0",
        priceNote: "Incluso no Navigo semanal",
        image: IMAGES.disney,
        link: { label: "Mapa RER A", url: "https://www.ratp.fr/en/getting-around/maps/rer-a" },
      },
      {
        time: "09h30 – 13h",
        title: "Disneyland Park",
        place: "Parque 1",
        desc: "Manhã: Big Thunder, Phantom Manor, Pirates do Caribe.",
        transport: "A pé",
        priceEur: "75 – 110",
        priceNote: "Ingresso 1 dia, 1 parque",
        image: IMAGES.disney,
        highlight: true,
        link: { label: "Comprar ingresso", url: "https://www.disneylandparis.com/en-usd/tickets/" },
      },
      {
        time: "13h – 14h",
        title: "Almoço no parque",
        place: "Disneyland",
        priceEur: "15 – 25",
        image: IMAGES.disney,
        link: { label: "Horários parque", url: "https://www.disneylandparis.com/en-usd/calendar/" },
      },
      {
        time: "14h – 17h",
        title: "Walt Disney Studios",
        place: "Parque 2",
        desc: "Se tiver Park Hopper, ou continuar no Parque 1.",
        priceEur: "incl.",
        image: IMAGES.disney,
      },
      {
        time: "17h – 20h",
        title: "Desfile e jantar",
        place: "Disneyland",
        desc: "Show da tarde/noite + jantar dentro do parque.",
        priceEur: "20 – 30",
        image: IMAGES.disney,
      },
      {
        time: "21h",
        title: "Retorno a Paris",
        place: "Hotel",
        transport: "RER A",
        priceEur: "0",
        image: IMAGES.aeroporto,
      },
    ],
  },
  {
    id: 5,
    emoji: "🛍️",
    weekday: "Sexta-feira",
    title: "Despedida de Paris",
    color: "#F9A825",
    accent: "#FFF2CC",
    date: "",
    summary: "Últimas compras de manhã e voo à tarde/noite.",
    activities: [
      {
        time: "08h",
        title: "Check-out",
        place: "Hotel",
        desc: "Saída do hotel. Guardar bagagem se permitido.",
        priceEur: "0",
        image: IMAGES.hotel,
      },
      {
        time: "08h30 – 10h30",
        title: "Últimas compras",
        place: "Le Marais / Saint-Germain",
        desc: "Mercado, padaria e souvenirs de despedida.",
        transport: "Metrô",
        priceEur: "10 – 30",
        image: IMAGES.bairro,
      },
      {
        time: "10h30 – 12h",
        title: "Musée d'Orsay",
        place: "7º arrondissement",
        desc: "Opcional — museu numa antiga estação de trem.",
        transport: "RER C / metrô",
        priceEur: "0 – 16",
        priceNote: "Grátis 1º domingo out–mar",
        image: IMAGES.orsay,
        link: { label: "Reservar d'Orsay", url: "https://billetterie.musee-orsay.fr/en-GB" },
      },
      {
        time: "12h – 13h30",
        title: "Almoço de despedida",
        place: "Perto do hotel",
        priceEur: "15 – 25",
        image: IMAGES.jantar,
      },
      {
        time: "14h – 16h",
        title: "Aeroporto",
        place: "CDG / Orly",
        desc: "Retorno ao hotel, bagagem e transfer (~1h CDG).",
        transport: "RER B / Navigo",
        priceEur: "0 – 14",
        image: IMAGES.aeroporto,
        link: { label: "Bilhete aeroporto", url: "https://www.iledefrance-mobilites.fr/en/tickets-fares/detail/paris-region-airport-ticket" },
      },
    ],
  },
];

const BOOKING_LINKS = [
  { cat: "Louvre", name: "Reservar ingresso", url: "https://ticket.louvre.fr/en", icon: "🎨" },
  { cat: "Torre Eiffel", name: "Comprar bilhete", url: "https://ticket.toureiffel.paris/en", icon: "🗼" },
  { cat: "Disneyland", name: "Ingressos Disney", url: "https://www.disneylandparis.com/en-usd/tickets/", icon: "🏰" },
  { cat: "Arco do Triunfo", name: "Reservar visita", url: "https://www.paris-arc-de-triomphe.fr/en/booking/book-a-ticket", icon: "🏛️" },
  { cat: "Navigo", name: "Passe semanal", url: "https://www.iledefrance-mobilites.fr/en/tickets-fares/detail/navigo-weekly-ticket", icon: "🚇" },
  { cat: "d'Orsay", name: "Reservar museu", url: "https://billetterie.musee-orsay.fr/en-GB", icon: "🖼️" },
  { cat: "Notre-Dame", name: "Visita catedral", url: "https://www.notredamedeparis.fr/en/visit/opening-times-and-access", icon: "⛪" },
  { cat: "Versailles", name: "Palácio", url: "https://www.chateauversailles.fr/visit/tickets", icon: "👑" },
];

const LOUVRE_FREE = [
  { date: "02/01/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "06/02/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "06/03/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "03/04/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "05/06/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "04/09/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "02/10/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "06/11/2026", day: "Sexta", time: "18h – 21h45" },
  { date: "04/12/2026", day: "Sexta", time: "18h – 21h45" },
];
